[package]
name = "fopomoro-mac"
version = "0.1.0"
description = "FoPoMoro macOS overlay app"
authors = ["Mafmudin"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "fopomoro_mac_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-notification = "2.3.3"
uuid = { version = "1.23.2", features = ["v4"] }
chrono = { version = "0.4.44", features = ["clock"] }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
dotenvy = "0.15.7"
tauri-plugin-window-state = "2.4.1"

